# Deep Learning with PyTorch

In [6]:
import torch

In [4]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))
#gives output between 1 and 0

In [5]:
### Generate some data
torch.manual_seed(7)

#randn will create tensor of normal variables i.e. random normal variables
features = torch.randn((1, 5))

# True weights for our data
weights = torch.randn_like(features)

# and a true bias term
bias = torch.randn((1, 1))

In [7]:
## Calculating the output of this network using the weights and bias tensors
y = activation(torch.sum(features*weights)+bias)
print(y)

#OR y=activation((features+weights).sum() + bias)

tensor([[0.1595]])


In [9]:
## Calculating the output of this network using matrix multiplication

#displays shape of tensor where features is the name of tensor
print(features.shape, weights.shape)
y = activation(torch.mm(features, weights.view(5,1))+bias)
print(y)

torch.Size([1, 5]) torch.Size([1, 5])
tensor([[0.1595]])


In [10]:
### Generating some data
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Defining the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

print("features: {}, \nn_input: {},\nn_hidden: {},\nn_output: {},\nW1: {},\nW2: {},\nB1: {},\nB2: {}"
      .format(features,n_input,n_hidden,n_output,W1,W2,B1,B2))

features: tensor([[-0.1468,  0.7861,  0.9468]]), 
n_input: 3,
n_hidden: 2,
n_output: 1,
W1: tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]]),
W2: tensor([[-1.6822],
        [ 0.3177]]),
B1: tensor([[0.1328, 0.1373]]),
B2: tensor([[0.2405]])


> **Exercise:** Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`. 

In [12]:
## Calculating output for multi-layer network

h = activation(torch.mm(features,W1)+B1)
print(h) #output of hidden layer

output = activation(torch.mm(h,W2)+B2)
print(output) #output of output layer

tensor([[0.6813, 0.4355]])
tensor([[0.3171]])
